#!/usr/bin/env bash

manifest_type="$1"

if [ -z "$manifest_type" ]; then
    echo "Usage: $0 <nginx|php>" >&2
    exit 1
fi

indent() {
    local expr='s/^/       /'

    if [ $(uname -s) = "Darwin" ]; then
        sed -l "$expr"
    else
        sed -u "$expr"
    fi
}

basedir="$( cd -P "$( dirname "$0" )" && pwd )"

source "$basedir/../conf/buildpack.conf"
source "$basedir/utils"
source "$basedir/s3"

validate_env

# make a temp directory
tempdir=$(mktmpdir manifest)
pushd $tempdir > /dev/null

echo "-----> Manifest for $manifest_type"

s3cmd ls -r s3://${S3_BUCKET} \
    | awk '{ print $4 }' \
    | sed "s/^package\///" \
    | grep "\.tgz$" \
    | grep "${manifest_type}" \
    | grep -v -e ".md5" \
    | sed -e "s/${manifest_type}-\([0-9.]*\)\\.tgz/\\1/" \
    | sed -e 's/.*\///' \
    > manifest.${manifest_type}

cat "manifest.${manifest_type}" | indent

echo
echo "-----> Uploading manifest for ${manifest_type} to S3"

s3_upload manifest.${manifest_type}
