#!/usr/bin/env bash

set -e

nginx_version="$1"

basedir="$( cd -P "$( dirname "$0" )" && pwd )"
source "$basedir/../conf/buildpack.conf"
source "$basedir/utils"
source "$basedir/s3"

validate_env

export PATH=${basedir}/../vendor/bin:$PATH

if [ -z "$nginx_version" ]; then
    echo "Usage: $0 <version>" >&2
    exit $E_ARG_MISSING
fi

if [ -z "$NGINX_ZLIB_VERSION" ]; then
    NGINX_ZLIB_VERSION=1.2.8
fi

if [ -z "$NGINX_PCRE_VERSION" ]; then
    NGINX_PCRE_VERSION=8.35
fi

zlib_version="$NGINX_ZLIB_VERSION"
pcre_version="$NGINX_PCRE_VERSION"

tempdir=$(mktmpdir nginx)
cd $tempdir

echo "-----> Downloading dependency PCRE ${pcre_version}"

curl -LO "http://sourceforge.net/projects/pcre/files/pcre/${pcre_version}/pcre-${pcre_version}.tar.gz"
tar -xzvf "pcre-${pcre_version}.tar.gz"

echo "-----> Downloading NGINX ${nginx_version}"

curl -LO "http://openresty.org/download/ngx_openresty-${nginx_version}.tar.gz"
tar -xzvf "ngx_openresty-${nginx_version}.tar.gz"

echo "-----> Uploading source to build server"

curl -LO "https://github.com/masterzen/nginx-upload-progress-module/archive/v0.9.1.tar.gz"
tar -xzvf "v0.9.1.tar.gz"
                                                                                                                                                                   
pushd ngx_openresty-${nginx_version} >/dev/null && \                                                                                                               
  ./configure \                                                                                                                                                    
    --prefix=/app/vendor/nginx \                                                                                                                                   
    --with-http_ssl_module \                                                                                                                                       
    --add-module=${tempdir}/nginx-upload-progress-module-0.9.1/ \                                                                                                  
    --with-http_mp4_module \                                                                                                                                       
    --with-pcre-jit \                                                                                                                                              
    --with-ipv6 && \                                                                                                                                               
  make && make install && \                                                                                                                                        
  popd > /dev/null

echo "-----> Uploading package to S3 https://${S3_URL}/package/ngx_openresty-${nginx_version}.tgz"

mkdir package
pushd /app/vendor/nginx >/dev/null
tar zcvf "${tempdir}/package/nginx-${nginx_version}.tgz" .
popd >/dev/null

s3_upload package/nginx-${nginx_version}.tgz
"$basedir/manifest" nginx
"$basedir/package-checksum" "nginx-${nginx_version}"

echo "-----> Done building NGINX package!"
