#!/usr/bin/env bash

set -e

basedir="$( cd -P "$( dirname "$0" )" && pwd )"
source "$basedir/../conf/buildpack.conf"
source "$basedir/utils"
source "$basedir/s3"

validate_env

package="$1"

cd $(mktmpdir s3)

echo "-----> Creating checksum for ${package}"

s3_download "package/${package}.tgz"

md5 "package/${package}.tgz" > "package/${package}.md5"
s3_upload "package/${package}.md5" "package"
