#!/usr/bin/env bash

basedir="$( cd -P "$( dirname "$0" )" && pwd )"
source "$basedir/../conf/buildpack.conf"
source "$basedir/utils"
source "$basedir/s3"

tempdir=$(mktmpdir composer)
cd $tempdir

curl -L http://getcomposer.org/composer.phar > composer.phar
md5 composer.phar > composer.phar.md5

mkdir composer
mv composer.phar composer
mv composer.phar.md5 composer

s3_upload "composer/composer.phar" "composer"
s3_upload "composer/composer.phar.md5" "composer"
