#!/usr/bin/env bash

basedir="$( cd -P "$( dirname "$0" )" && pwd )"
source "$basedir/../conf/buildpack.conf"
source "$basedir/utils"
source "$basedir/s3"

tempdir=$(mktmpdir jq)
cd $tempdir

echo "----> Vendoring 'jq'"
curl -L http://stedolan.github.io/jq/download/linux64/jq > jq_bin

mkdir jq
mv jq_bin jq/jq
s3_upload jq/jq
